AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/application.rb'
    - 'db/schema.rb'
Metrics/BlockLength:
  IgnoredMethods: [ 'describe', 'context' ]
  Exclude:
    - 'db/seeds.rb'
Style/Documentation:
  Exclude:
    - 'app/controllers/*'